### ISSUE TITLE
[bug]

### ISSUE THREAD

**Issue by OmarShawky1** [tchar/ulauncher-albert-calculate-anything#34] opened 2021-11-30 09:02 UTC
## Describe the bug
Does not give time at any place except my own place. and if i gave it my place it does not work

## To Reproduce
`time at NYC` or `time at Calif` gives my own timezone but `time at cairo` or `time at cairo egypt` does not give anything.

## Expected behavior
Gives the current time at target city.

## Logs
If possible please provide the logs from the [log](../docs/API.md#log-directories) directory
Supose your username is `username`:
- Linux: `/home/username/.cache/com.github.tchar.calculate-anything/log`
- Windows: `'C:\Users\username\AppData\Local\tchar\com.github.tchar.calculate-anything\Logs`
- macOS: `/Users/username/Library/Logs/com.github.tchar.calculate-anything`
You can get then in a zip file and post it with the issue.

## Screenshots
![NYC time example](https://user-images.githubusercontent.com/51538094/144016520-87b2186b-3fcf-4a05-aa27-519a77550048.png)

## Desktop (please complete the following information)
 - OS: Elementary OS 5.1.7 (based on Ubuntu Bionic 18.04 LTS)

**Comment by tchar** [comment] 2021-12-01 03:04
Hey @OmarShawky1 

Did the extension work at any point, or did it have this behavior since ever.
Also could you please provide the logs after you run the command?
If you reinstall is the problem fixed?

Thanks
-T

**Comment by OmarShawky1** [comment] 2021-12-01 07:05
Hey @tchar 

1. Never worked.
2. Issue Persists

**Comment by tchar** [comment] 2021-12-01 21:20
Hello @OmarShawky1 

Would you mind providing the logs from ~/.cache/com.github.tchar.calculate-anything/log

**Comment by OmarShawky1** [comment] 2021-12-03 14:20
1. Very sorry for the delay
2. I read the logs myself and discovered that i did not read your README XD, all i need is tl install `pip3 install pytz` and it worked as smooth as butter.

**Comment by tchar** [comment] 2021-12-04 05:14
Yes, the problem is that NYC, is not the alias in my database. I have a repo of the datebase itself, but its a pain in the ass to map every city's alias.

For now you can put it in the default cities in the settings and the `time` command will give you the time in New York City by default under your local time without specifying the location.

I am closing this since `pip3 install pytz` fixes it and its not an issue.

Cheers,

- T

**Closed by tchar** 2021-12-04 05:14 UTC
Labels: bug

**Comment by OmarShawky1** [comment] 2021-12-10 07:02
Just a small hint, California does not appear in time as following:
![image](https://user-images.githubusercontent.com/51538094/145531462-e63aee58-6e9f-4d25-9829-fd53efa5a781.png)
