### ISSUE TITLE
Nothing but math is working

### ISSUE THREAD

**Issue by mohammad17112003** [tchar/ulauncher-albert-calculate-anything#45] opened 2023-01-11 20:22 UTC
No currency or unit conversion

**Comment by Alonely0** [comment] 2023-01-22 00:58
Same. I'll leave a traceback here:

**Comment by securegh** [comment] 2023-02-26 04:59
No currency or unit conversion is working for me as well 😥

**Comment by stingray21** [comment] 2023-04-11 17:52
same for me, there has been #42  open since last Dec, but unfortunately no fix yet

**Comment by 7549brijesh** [comment] 2023-04-12 04:37
now I am started thinking that this project has been abandoned
anyone here to say me that my statement is wrong?

**Comment by PrathamBhatTech** [comment] 2023-06-16 08:20
I have the same issue.

**Comment by stingray21** [comment] 2023-07-13 01:58
Is there any hope for this to get fixed? It would be pretty sad for this great extension to die. but in the current state it is almost useless, at least for my use cases.

**Comment by stingray21** [comment] 2023-08-08 16:23
It is (was) a very useful extension, unfortunately just not with this bug 😢

**Comment by arunstop** [comment] 2023-09-03 13:02
2 weeks ago, this works perfectly, now it's just dead? I wonder if it's some dependency problem?

**Comment by igorsantos07** [comment] 2023-11-10 23:31
I can confirm this is a dupe of #42 for me - you can find the error dump if you execute `ulauncher` from CLI.

**Comment by tchar** [comment] 2024-03-28 00:06
Can you try reinstalling the app and letting me know if it worked? I posed a fix #48 and also in #46 I explain what is happening [here](https://github.com/tchar/ulauncher-albert-calculate-anything/pull/46#issuecomment-2024021876)

**Closed** 2024-03-28 01:47 UTC
